

services:
  backend:
    build: .
    container_name: people_api_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=people_api.settings
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo:6.0
    container_name: people_api_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: people_api_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=

volumes:
  mongo_data: